export const defaultSongs = [
  {
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    year: 1975,
    spotifyUri: 'spotify:track:3z8h0TU7ReDPLIbEnYhWZb',
  },
  {
    title: 'Fix You',
    artist: 'Coldplay',
    year: 2005,
    spotifyUri: 'spotify:track:7LVHVU3tWfcxj5aiPFEW4Q',
  },
  {
    title: 'Hotel California',
    artist: 'Eagles',
    year: 1976,
    spotifyUri: 'spotify:track:40riOy7x9W7GXjyGp4pjAv',
  },
  {
    title: 'Roller Coaster',
    artist: 'Danny Vera',
    year: 2019,
    spotifyUri: 'spotify:track:4h9wh7iOZ0GGn8QVp4RAOB',
  },
  {
    title: 'Piano Man',
    artist: 'Billy Joel',
    year: 1973,
    spotifyUri: 'spotify:track:3FCto7hnn1shUyZL42YgfO',
  },
  {
    title: 'Better Days',
    artist: 'Dermot Kennedy',
    year: 2021,
    spotifyUri: 'spotify:track:3oQHoS8FakxqCHKzycNBvf',
  },
  {
    title: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    year: 1971,
    spotifyUri: 'spotify:track:5CQ30WqJwcep0pYcV4AMNc',
  },
  {
    title: 'Black',
    artist: 'Pearl Jam',
    year: 1991,
    spotifyUri: 'spotify:track:5Xak5fmy089t0FYmh3VJiY',
  },
  {
    title: 'Avond',
    artist: 'Boudewijn de Groot',
    year: 1997,
    spotifyUri: 'spotify:track:4XbuyS8yB9Cq9XYj0QEbXV',
  },
  {
    title: 'Wish You Were Here',
    artist: 'Pink Floyd',
    year: 1975,
    spotifyUri: 'spotify:track:6mFkJmJqdDVQ1REhVfGgd1',
  },
  {
    title: 'Child in Time',
    artist: 'Deep Purple',
    year: 1970,
    spotifyUri: 'spotify:track:3QV1jQVyZgHQlLbKYQhQ1h',
  },
  {
    title: 'Brothers in Arms',
    artist: 'Dire Straits',
    year: 1985,
    spotifyUri: 'spotify:track:4knL4iPxPOZjQzTUlELGSY',
  },
  {
    title: 'Africa',
    artist: 'Toto',
    year: 1982,
    spotifyUri: 'spotify:track:2374M0fQpWi3dLnB54qaLX',
  },
  {
    title: 'Shine On You Crazy Diamond',
    artist: 'Pink Floyd',
    year: 1975,
    spotifyUri: 'spotify:track:32dnKMni3I3gwUbWp4mi45',
  },
  {
    title: 'Comfortably Numb',
    artist: 'Pink Floyd',
    year: 1979,
    spotifyUri: 'spotify:track:6GDJDUqQxeGF6g8zvvAHei',
  },
  {
    title: 'November Rain',
    artist: "Guns N' Roses",
    year: 1991,
    spotifyUri: 'spotify:track:3YRCqOhFifThpSRFJ1VWFM',
  },
  {
    title: 'One',
    artist: 'U2',
    year: 1991,
    spotifyUri: 'spotify:track:3G69vJMWsX6ZohTykad2AU',
  },
  {
    title: 'Heroes',
    artist: 'David Bowie',
    year: 1977,
    spotifyUri: 'spotify:track:7Jh1bpe76CNTCgdgAdBw4Z',
  },
  {
    title: 'Purple Rain',
    artist: 'Prince',
    year: 1984,
    spotifyUri: 'spotify:track:54X78diSLoUDI3joC2bjMz',
  },
  {
    title: 'Somebody to Love',
    artist: 'Queen',
    year: 1976,
    spotifyUri: 'spotify:track:4rDbp1vnvEhieiccprPMdI',
  },
];
